---
- name: "(Handler: All OSs) Run NGINX"
  block:
    - name: "(Handler: All OSs) Start NGINX"
      service:
        name: nginx
        state: started
        enabled: yes
      notify: "(Handler: All OSs) Check NGINX"

    - name: "(Handler: All OSs) Check NGINX"
      command: "nginx -t"
      notify: "(Handler: All OSs) Start NGINX"
      changed_when: false

    - name: "(Handler: All OSs) Reload NGINX"
      command: "nginx -s reload"
      changed_when: false
  when:
    - nginx_config_start | bool
    - not ansible_check_mode
